"""
core/report.py -- Report Generator

Generates Markdown and JSON reports from scan findings.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import List

from jinja2 import BaseLoader, Environment

from core.config import Config
from core.finding_quality import score_finding, summarize_trust
from core.models import Finding, Scan, Severity

_SEV_ORDER = {
    Severity.CRITICAL: 0,
    Severity.HIGH: 1,
    Severity.MEDIUM: 2,
    Severity.LOW: 3,
    Severity.INFO: 4,
}

_MD_TEMPLATE = """# ZeroDay AI Security Report
**Scan ID:** {{ scan.id }}
**Target:** {{ scan.target }}
**Started:** {{ scan.started_at }}
**Finished:** {{ scan.finished_at }}
**Total Findings:** {{ findings|length }}

---

## Summary

| Severity | Count |
|----------|-------|
| Critical | {{ findings | selectattr('severity', 'equalto', 'critical') | list | length }} |
| High     | {{ findings | selectattr('severity', 'equalto', 'high') | list | length }} |
| Medium   | {{ findings | selectattr('severity', 'equalto', 'medium') | list | length }} |
| Low      | {{ findings | selectattr('severity', 'equalto', 'low') | list | length }} |
| Info     | {{ findings | selectattr('severity', 'equalto', 'info') | list | length }} |

## Trust Profile

| Trust Tier | Count |
|------------|-------|
| Verified   | {{ trust_summary.verified }} |
| Strong     | {{ trust_summary.strong }} |
| Moderate   | {{ trust_summary.moderate }} |
| Weak       | {{ trust_summary.weak }} |

---

## Findings

{% for f in findings %}
### {{ loop.index }}. {{ f.title }}

| Field | Value |
|-------|-------|
| **Severity** | {{ f.severity.upper() }} |
| **Category** | {{ f.category }} |
| **Agent** | {{ f.agent }} |
{% if f.file_path %}| **File** | `{{ f.file_path }}` |{% endif %}
{% if f.line_number %}| **Line** | {{ f.line_number }} |{% endif %}
{% if f.url %}| **URL** | {{ f.url }} |{% endif %}
{% if f.cvss_score %}| **CVSS** | {{ f.cvss_score }} |{% endif %}
{% if f.cve_ids %}| **CVEs** | {{ f.cve_ids }} |{% endif %}
| **Confidence** | {{ (f.confidence * 100)|int }}% |
| **Trust** | {{ f.trust.tier.upper() }} ({{ f.trust.score }}/100) |

**Description:**
{{ f.description }}

{% if f.trust.signals %}
**Evidence Signals:** {{ f.trust.signals | join(', ') }}
{% endif %}

{% if f.code_snippet %}
**Vulnerable Code:**
```
{{ f.code_snippet }}
```
{% endif %}

{% if f.poc %}
**Proof of Concept:**
{{ f.poc }}
{% endif %}

{% if f.remediation %}
**Remediation:**
{{ f.remediation }}
{% endif %}

---
{% endfor %}

*Generated by ZeroDay AI at {{ generated_at }}*
"""


class ReportGenerator:
    def __init__(self, config: Config):
        self.config = config
        self._env = Environment(loader=BaseLoader())
        self._env.filters["selectattr"] = self._selectattr

    async def generate(self, scan: Scan, findings: List[Finding]) -> List[str]:
        """Generate all configured report formats. Returns list of file paths."""
        out_dir = Path(self.config.reporting.output_dir) / scan.id[:8]
        out_dir.mkdir(parents=True, exist_ok=True)

        sorted_findings = sorted(findings, key=lambda f: _SEV_ORDER.get(f.severity, 5))

        paths = []
        fmts = self.config.reporting.formats

        if "json" in fmts:
            report_json = self._to_json(scan, sorted_findings)
            p = out_dir / "report.json"
            p.write_text(json.dumps(report_json, indent=2, default=str), encoding="utf-8")
            paths.append(str(p))

        if "markdown" in fmts:
            p = out_dir / "report.md"
            p.write_text(self._render_markdown(scan, sorted_findings), encoding="utf-8")
            paths.append(str(p))

        return paths

    def _render_markdown(self, scan: Scan, findings: List[Finding]) -> str:
        tpl = self._env.from_string(_MD_TEMPLATE)
        findings_data = []
        for finding in findings:
            trust = score_finding(finding)
            findings_data.append(
                {
                    "title": finding.title,
                    "severity": finding.severity.value,
                    "category": finding.category.value if finding.category else "other",
                    "agent": finding.agent.value if finding.agent else "unknown",
                    "file_path": finding.file_path,
                    "line_number": finding.line_number,
                    "url": finding.url,
                    "cvss_score": finding.cvss_score,
                    "cve_ids": finding.cve_ids,
                    "confidence": finding.confidence or 0.8,
                    "description": finding.description,
                    "code_snippet": finding.code_snippet,
                    "poc": finding.poc,
                    "remediation": finding.remediation,
                    "trust": trust,
                }
            )
        return tpl.render(
            scan=scan,
            findings=findings_data,
            trust_summary=summarize_trust(findings),
            generated_at=datetime.utcnow().isoformat(),
        )

    @staticmethod
    def _to_json(scan: Scan, findings: List[Finding]) -> dict:
        return {
            "scan": {
                "id": scan.id,
                "target": scan.target,
                "status": scan.status.value if scan.status else "unknown",
                "started_at": str(scan.started_at),
                "finished_at": str(scan.finished_at),
                "finding_count": len(findings),
                "trust_summary": summarize_trust(findings),
            },
            "findings": [
                {
                    "id": finding.id,
                    "title": finding.title,
                    "severity": finding.severity.value,
                    "category": finding.category.value if finding.category else "other",
                    "agent": finding.agent.value if finding.agent else "unknown",
                    "file_path": finding.file_path,
                    "line_number": finding.line_number,
                    "url": finding.url,
                    "parameter": finding.parameter,
                    "payload": finding.payload,
                    "description": finding.description,
                    "code_snippet": finding.code_snippet,
                    "poc": finding.poc,
                    "remediation": finding.remediation,
                    "cve_ids": finding.cve_ids,
                    "cvss_score": finding.cvss_score,
                    "confidence": finding.confidence,
                    "trust": score_finding(finding),
                    "created_at": str(finding.created_at),
                }
                for finding in findings
            ],
        }

    @staticmethod
    def _selectattr(iterable, attr, test_name=None, value=None):
        """Jinja2 selectattr filter: supports selectattr(attr, 'equalto', value)."""
        for item in iterable:
            item_val = item.get(attr) if isinstance(item, dict) else getattr(item, attr, None)

            if test_name == "equalto":
                if item_val == value:
                    yield item
            elif item_val:
                yield item
